### PR TITLE
Support for swiftmailer v6.0

### PR DESCRIPTION
**Pull request by TerjeBr**
This will make the parser be compitable with swiftmailer v.6.0 and later.
Fixes issue #5

Found no way to be backwards compitable with earlier versions of swiftmailer, so you should probably make a major version bump for this.

### CODE REVIEW

**Comment by TerjeBr** [comment]
Hi @goetas . Have you had a chance to look at this yet?

**Comment by hovsep** [comment]
+1 for this PR. I want to use the parser with SwiftMailer 6+

Thank you guys for nice job

**Comment by TerjeBr** [comment]
Thank you for merging it.

**Comment by pribeirojtm** [comment]
Hi there. Is it possible for you to release a tag on this for branch 1.0.x series? I'm asking because I'm working with php 7.0.x and , for now, I cant use 2.x version. 
Thanks.

**Pull request merged**
